[package]
name = "allanime"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
reqwest.workspace = true
eyre.workspace = true
serde_json.workspace = true


[dev-dependencies]
tokio.workspace = true
